sources:
  - name: ssov
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/psytama/dopex-ssov
    transforms:
      - prefix:
          value: ssov_
          includeRootOperations: true
  - name: straddles
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/psytama/dopex-straddles
    transforms:
      - prefix:
          value: straddles_
          includeRootOperations: true
  - name: straddles_polygon
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/psytama/dopex-straddles-polygon
    transforms:
      - prefix:
          value: straddles_polygon
          includeRootOperations: true
  - name: optionScalps
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/aercwarden/dopex-option-scalps
    transforms:
      - autoPagination:
          validateSchema: true
  - name: zdte
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/garyunwin42/zdte
    transforms:
      - autoPagination:
          validateSchema: true

documents:
  - ./src/graphql/**/*.graphql
