/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import { Provider } from '@ethersproject/providers';
import type {
  IGMXPositionManager,
  IGMXPositionManagerInterface,
} from '../IGMXPositionManager';

const _abi = [
  {
    inputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    name: 'executeRequiredAction',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    name: 'getRequiredAction',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'requiredAction',
    outputs: [
      {
        internalType: 'enum IGMXPositionManager.RequiredAction',
        name: '',
        type: 'uint8',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
];

export class IGMXPositionManager__factory {
  static readonly abi = _abi;
  static createInterface(): IGMXPositionManagerInterface {
    return new utils.Interface(_abi) as IGMXPositionManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGMXPositionManager {
    return new Contract(address, _abi, signerOrProvider) as IGMXPositionManager;
  }
}
