/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import { Provider } from '@ethersproject/providers';
import type {
  IOptionPricing,
  IOptionPricingInterface,
} from '../IOptionPricing';

const _abi = [
  {
    inputs: [
      {
        internalType: 'bool',
        name: 'isPut',
        type: 'bool',
      },
      {
        internalType: 'uint256',
        name: 'expiry',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'strike',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'lastPrice',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'baseIv',
        type: 'uint256',
      },
    ],
    name: 'getOptionPrice',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
];

export class IOptionPricing__factory {
  static readonly abi = _abi;
  static createInterface(): IOptionPricingInterface {
    return new utils.Interface(_abi) as IOptionPricingInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IOptionPricing {
    return new Contract(address, _abi, signerOrProvider) as IOptionPricing;
  }
}
